### ISSUE TITLE
Helper Functions not catching errors

### ISSUE THREAD

**Issue by lakhassane** [OpenFn/language-salesforce#12]
We encountered a behavior where we are having green checks using this language-package while there is an error in job run.

We should ensure that errors are catched and reject whenever they occur.

Check this comment for more context.

https://github.com/OpenFn/lwala/issues/23#issuecomment-690765354

## Specific request
Make the appropriate changes in `language-salesfore` in order to catch errors and reject them when they occur.

### state.json
Test with Lwala Salesforce sandbox. See LP for creds. 
Use `sample_data/state_personB.json` to test. 

### expression.js
Use `MOH513-Enroll-Household-in-SF.js`

### adaptor
Use `Adaptor.js` and not `FakeAdaptor.js`.

**Comment by taylordowns2000** [comment]
I'd love to see the PR here. My question is whether we need to `catch` _then_ `reject` errors, or if they're uncaught will they simply bubble up.

**Comment by aleksa-krolls** [comment]
@taylordowns2000 please let me know when live on prod

**Comment by taylordowns2000** [comment]
As discussed offline and in #13 , `combine` wasn't being used properly, and created a situation where errors could be thrown but since the run already "`Finished.`" on a success response from salesforce, it was treated as a success. you _could_ open an issue on `language-common`, but this isn't a bug, so much as improper use of that very strange and specific helper function.
