### ISSUE TITLE
Add docs and in-line docs for `relationship(...)` helper

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/language-salesforce#24]
I don't see `relationship(...)` documented in the job studio... this is a commonly used helper function, so please make sure it's available in the job studio in-line docs, as well as the documentation side bar. Thank you!

**Comment by aleksa-krolls** [comment]
@lakhassane Thanks! is there a difference between `relationship(...)` and `lookup(...)` or are these the same? If the same... shouldn't we just maintain one? 
cc @taylordowns2000

**Comment by aleksa-krolls** [comment]
@lakhassane @taylordowns2000 please note my question above

**Comment by taylordowns2000** [comment]
@lakhassane , look how `relationship` is slightly [more flexible](https://github.com/OpenFn/language-salesforce/blob/master/src/sourceHelpers.js#L36-L41) and how `lookup` must be given [a JSON path](https://github.com/OpenFn/language-salesforce/blob/master/src/sourceHelpers.js#L16-L18).

There are currently a total of 16 jobs that use `lookup`... half are version locked to `v0.1.6` and the other half to `v1.3.2`. My proposal is to drop `lookup` and maintain relationship and to move it into `Adaptor.js` (deleting `sourceHelpers.js` entirely) so that it gets proper front-end documentation generated.

If you're on board with this, please make it happen!

**Comment by aleksa-krolls** [comment]
Agreed! @lakhassane moving to backlog

**Comment by lakhassane** [comment]
Implemented as discussed
